# Generated by Django 6.0 on 2025-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100)),
                ('amount_sats', models.IntegerField()),
                ('invoice', models.TextField()),
                ('payment_hash', models.CharField(max_length=200)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
